// todo make load csv?
const proficiencies = {
  "ARC-L1": {
    Quantainium: "0%",
    Bexalite: "0%",
    Taranite: "3%",
    Borase: "-3%",
    Laranite: "4%",
    Agricium: "2%",
    Hephaestanite: "-2%",
    Titanium: "0%",
    Diamond: "4%",
    Gold: "-6%",
    Copper: "0%",
    Beryl: "-9%",
    Tungsten: "05",
    Corundum: "2%",
    Quartz: "0%",
    Aluminium: "4%",
  },
  "CRU-L1": {
    Quantainium: "3%",
    Bexalite: "5%",
    Taranite: "0%",
    Borase: "0%",
    Laranite: "0%",
    Agricium: "0%",
    Hephaestanite: "0%",
    Titanium: "4%",
    Diamond: "0%",
    Gold: "4%",
    Copper: "0%",
    Beryl: "0%",
    Tungsten: "2%",
    Corundum: "-4%",
    Quartz: "0%",
    Aluminium: "0%",
  },
  "HUR-L1": {
    Quantainium: "-6%",
    Bexalite: "0%",
    Taranite: "0%",
    Borase: "0%",
    Laranite: "4%",
    Agricium: "3%",
    Hephaestanite: "0%",
    Titanium: "2%",
    Diamond: "0%",
    Gold: "0%",
    Copper: "10%",
    Beryl: "3%",
    Tungsten: "0%",
    Corundum: "0%",
    Quartz: "0%",
    Aluminium: "2%",
  },
  "HUR-L2": {
    Quantainium: "0%",
    Bexalite: "-3%",
    Taranite: "-4%",
    Borase: "4%",
    Laranite: "0%",
    Agricium: "0%",
    Hephaestanite: "2%",
    Titanium: "-3%",
    Diamond: "0%",
    Gold: "0%",
    Copper: "3%",
    Beryl: "0%",
    Tungsten: "0%",
    Corundum: "0%",
    Quartz: "0%",
    Aluminium: "2%",
  },
  "MIC-L1": {
    Quantainium: "+2%",
    Bexalite: "+4%",
    Taranite: "0%",
    Borase: "+4%",
    Laranite: "-6%",
    Agricium: "0%",
    Hephaestanite: "+5%",
    Titanium: "0%",
    Diamond: "+5%",
    Gold: "0%",
    Copper: "0%",
    Beryl: "+3%",
    Tungsten: "-3%",
    Corundum: "0%",
    Quartz: "+3%",
    Aluminium: "-8%",
  },
};

export function getProficiencies(refinery) {
  return proficiencies[refinery];
}
