name: ci

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    pull_request:
      types: [opened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install and Test
        run: |
          npm install
          npm run test
